'''The game is that the computer "thinks" about a number and we have to guess it. On every guess, the computer will tell us if our guess was smaller or bigger than the hidden number. The game ends when we find the number.Also Define no of attemps took to find this hidden number.(Hidden number lies between 0 - 100)'''

import random                                         # importing random file to generate a random number

def guess(n):                                         # defining a function to guess hidden number
    c=1                                               # taken variable to count the number of chances
    while True:                                       # taken a while loop to run upto number is guessed
        k=int(input("Guess a number: "))              # taken a variable to guess a number
        if(k==n):                                     # if guessed number is equal to hidden number
            print("You have won the game")            # printing that user has guessed the number
            break                                     # after guessing there is no need for while so break it
        else:                                         # if not
            if(k<n):                                  # and if guessed number lessthan hiddden
                print("Hidden number is greater, Guess again") # print hidden is greater
            else:                                     # if not
                print("Hidden number is lesser, Guess again") # print hidden is lesser
        c+=1                                          # counting the chances adding 1
    print("You have taken",c,"chances to find the hidden number",n) # printing the chances taken after number is guessed

    
H= random.randint(0,100)                              # taken a variable to store random number generated by randint in range of 0-100
guess(H)                                              # calling the function to guess the number

