'''The game is that the computer "thinks" about a number and we have to guess it. On every guess, the computer will tell us if our guess was smaller or bigger than the hidden number. The game ends when we find the number.Also Define no of attemps took to find this hidden number.(Hidden number lies between 0 - 100)'''

import random                                         # importing random file to generate a random number

def guess(n):                                         # defining a function to guess hidden number
    c=1                                               # taken variable to count the number of chances 
    a=0                                               # taken a variable for reference to check thet user guessed the number  
    while c<=5:                                       # As there are 5 chances to guess while loop runs for 5 times
        k=int(input("Guess a number: "))              # taken a variable to guess a number
        if(k==n):                                     # if guessed number is equal to hidden number
            print("Hidden number is",H,",You have won the game in",c,"chances") # printing that user has guessed the number
            a=1                                       # making the variable for reference to 1 to know that number has been guessed 
            break                                     # after guessing there is no need for while so break it
        elif(c!=5):                                   # if the count not equal to 5
            if(k<n):                                  # and if guessed number lessthan hiddden
                print("Hidden number is greater, Guess again") # print hidden is greater
            else:                                     # if not
                print("Hidden number is lesser, Guess again") # print hidden is lesser
        c+=1                                          # counting the chances adding 1
    if(a==0):                                         # if reference variable is 0 then user havent guessed the number 
        print("Sorry, Your chances are over")         # printing chances are over
    
H= random.randint(0,100)                              # taken a variable to store random number generated by randint in range of 0-100
guess(H)                                              # calling the function to guess the number


